### ISSUE TITLE
Dear author，some questions need your help

### ISSUE THREAD

**Issue by Creazy-MR** [MusingZone/FL-stratified-client-selection#1]
Dear author,when i run your code with iid partition  ,i find that the top accuracy(200 iter) is lower than McMahan‘s work, and more slowly. why is it, thanks!

**Comment by Creazy-MR** [comment]
and when i setting iter to 500, the program not run and exit()
![image](https://user-images.githubusercontent.com/59354418/171628056-873e1958-cad9-447c-97b9-d637f8123dcd.png)

**Comment by Creazy-MR** [comment]
@MusingZone thanks

**Comment by MusingZone** [comment]
> Dear author,when i run your code with iid partition ,i find that the top accuracy(200 iter) is lower than McMahan‘s work, and more slowly. why is it, thanks!

Note that there's a parameter termed as "sample_ratio" in our experiment, which means that only a percentage of clients is sampled during each round. We consider 100 clients in all our datasets and use thus default sample_ratio=0.1, undoubtedly it will affect the training effect and the prediction accuracy.


> and when i setting iter to 500, the program not run and exit() ![image](https://user-images.githubusercontent.com/59354418/171628056-873e1958-cad9-447c-97b9-d637f8123dcd.png)

There is a mechanism for protecting the previous experiment results from being overwritten by the latest ones, which is achieved through filename comparison. If you do want to do the overwriting operation, simply set the "--force" parameter to _True_.

**Comment by Creazy-MR** [comment]
@MusingZone  Thanks for your timely reply!  Your article is very interesting！I will continue to study this work！
